#ifndef MACROS_H
#define MACROS_H

#include <stm32f7xx.h>

#define GPIO_AFRL_AFR0	GPIO_AFRL_AFRL0
#define GPIO_AFRL_AFR1	GPIO_AFRL_AFRL1
#define GPIO_AFRL_AFR2	GPIO_AFRL_AFRL2
#define GPIO_AFRL_AFR3	GPIO_AFRL_AFRL3
#define GPIO_AFRL_AFR4	GPIO_AFRL_AFRL4
#define GPIO_AFRL_AFR5	GPIO_AFRL_AFRL5
#define GPIO_AFRL_AFR6	GPIO_AFRL_AFRL6
#define GPIO_AFRL_AFR7	GPIO_AFRL_AFRL7

#define GPIO_AFRL_AFR0_Pos	GPIO_AFRL_AFRL0_Pos
#define GPIO_AFRL_AFR1_Pos	GPIO_AFRL_AFRL1_Pos
#define GPIO_AFRL_AFR2_Pos	GPIO_AFRL_AFRL2_Pos
#define GPIO_AFRL_AFR3_Pos	GPIO_AFRL_AFRL3_Pos
#define GPIO_AFRL_AFR4_Pos	GPIO_AFRL_AFRL4_Pos
#define GPIO_AFRL_AFR5_Pos	GPIO_AFRL_AFRL5_Pos
#define GPIO_AFRL_AFR6_Pos	GPIO_AFRL_AFRL6_Pos
#define GPIO_AFRL_AFR7_Pos	GPIO_AFRL_AFRL7_Pos

#define GPIO_AFRH_AFR8	GPIO_AFRH_AFRH0
#define GPIO_AFRH_AFR9	GPIO_AFRH_AFRH1
#define GPIO_AFRH_AFR10	GPIO_AFRH_AFRH2
#define GPIO_AFRH_AFR11	GPIO_AFRH_AFRH3
#define GPIO_AFRH_AFR12	GPIO_AFRH_AFRH4
#define GPIO_AFRH_AFR13	GPIO_AFRH_AFRH5
#define GPIO_AFRH_AFR14	GPIO_AFRH_AFRH6
#define GPIO_AFRH_AFR15	GPIO_AFRH_AFRH7

#define GPIO_AFRH_AFR8_Pos	GPIO_AFRH_AFRH0_Pos
#define GPIO_AFRH_AFR9_Pos	GPIO_AFRH_AFRH1_Pos
#define GPIO_AFRH_AFR10_Pos	GPIO_AFRH_AFRH2_Pos
#define GPIO_AFRH_AFR11_Pos	GPIO_AFRH_AFRH3_Pos
#define GPIO_AFRH_AFR12_Pos	GPIO_AFRH_AFRH4_Pos
#define GPIO_AFRH_AFR13_Pos	GPIO_AFRH_AFRH5_Pos
#define GPIO_AFRH_AFR14_Pos	GPIO_AFRH_AFRH6_Pos
#define GPIO_AFRH_AFR15_Pos	GPIO_AFRH_AFRH7_Pos

#define GPIO_MODER(b, p, m)	(b)->MODER = \
	(((b)->MODER & ~GPIO_MODER_MODER##p) | ((m) << GPIO_MODER_MODER##p##_Pos))
#define GPIO_AFRL(b, p, m)	(b)->AFR[0] = \
	(((b)->AFR[0] & ~GPIO_AFRL_AFR##p) | ((m) << GPIO_AFRL_AFR##p##_Pos))
#define GPIO_AFRH(b, p, m)	(b)->AFR[1] = \
	(((b)->AFR[1] & ~GPIO_AFRH_AFR##p) | ((m) << GPIO_AFRH_AFR##p##_Pos))
#define GPIO_OTYPER_PP(b, p)	(b)->OTYPER &= ~GPIO_OTYPER_OT_##p
#define GPIO_OTYPER_OD(b, p)	(b)->OTYPER |= GPIO_OTYPER_OT_##p
#define GPIO_OSPEEDR(b, p, m)	(b)->OSPEEDR = \
	(((b)->OSPEEDR & ~GPIO_OSPEEDER_OSPEEDR##p) | ((m) << GPIO_OSPEEDER_OSPEEDR##p##_Pos))
#define GPIO_PUPDR(b, p, m)	(b)->PUPDR = \
	(((b)->PUPDR & ~GPIO_PUPDR_PUPDR##p) | ((m) << GPIO_PUPDR_PUPDR##p##_Pos))
#define GPIO_PUPDR_UP	0b01
#define GPIO_PUPDR_DOWN	0b10

#endif // MACROS_H
